export const btnList = [
    { name: 'Generate' },
    { name: 'Reset' },
    { name: 'Copy' },
    { name: 'Shuffle' },
    { name: 'Download' },
];

export const treeData = [
    {
        title: "Asia",
        value: "1",
        key: "1",
        children: [
            { "title": "Thailand", "value": "th", "key": "th" },
            { "title": "China", "value": "cn", "key": "cn" },
            { "title": "Indonesia", "value": "id", "key": "id" },
            { "title": "Taiwan", "value": "tw", "key": "tw" },
            { "title": "Yemen", "value": "ye", "key": "ye" },
            { "title": "Philippines", "value": "ph", "key": "ph" },
            { "title": "India", "value": "in", "key": "in" },
            { "title": "Pakistan", "value": "pk", "key": "pk" },
            { "title": "South Korea", "value": "kr", "key": "kr" },
            { "title": "Japan", "value": "jp", "key": "jp" },
            { "title": "Malaysia", "value": "my", "key": "my" },
            { "title": "Saudi Arabia", "value": "sa", "key": "sa" },
            { "title": "Vietnam", "value": "vn", "key": "vn" },
            { "title": "Hong Kong", "value": "hk", "key": "hk" },
            { "title": "Syria", "value": "sy", "key": "sy" },
            { "title": "Singapore", "value": "sg", "key": "sg" }
        ],
    },
    {
        title: "America",
        value: "2",
        key: "2",
        children: [
            { "title": "Chile", "value": "cl", "key": "cl" },
            { "title": "Uruguay", "value": "uy", "key": "uy" },
            { "title": "Dominican Republic", "value": "do", "key": "do" },
            { "title": "Venezuela", "value": "ve", "key": "ve" },
            { "title": "Brazil", "value": "br", "key": "br" },
            { "title": "Argentina", "value": "ar", "key": "ar" },
            { "title": "United States", "value": "us", "key": "us" },
            { "title": "Colombia", "value": "co", "key": "co" },
            { "title": "Canada", "value": "ca", "key": "ca" },
            { "title": "Mexico", "value": "mx", "key": "mx" }
        ],
    },
    {
        title: "Europe",
        value: "3",
        key: "3",
        children: [
            { "title": "Bailiwick of Jersey", "value": "je", "key": "je" },
            { "title": "Italy", "value": "it", "key": "it" },
            { "title": "Monaco", "value": "mc", "key": "mc" },
            { "title": "Belgium", "value": "be", "key": "be" },
            { "title": "Spain", "value": "es", "key": "es" },
            { "title": "Austria", "value": "at", "key": "at" },
            { "title": "Croatia (Hrvatska)", "value": "hr", "key": "hr" },
            { "title": "Denmark", "value": "dk", "key": "dk" },
            { "title": "Greece", "value": "gr", "key": "gr" },
            { "title": "Norway", "value": "no", "key": "no" },
            { "title": "Guernsey", "value": "gg", "key": "gg" },
            { "title": "Netherlands", "value": "nl", "key": "nl" },
            { "title": "San Marino", "value": "sm", "key": "sm" },
            { "title": "Portugal", "value": "pt", "key": "pt" },
            { "title": "Russia", "value": "ru", "key": "ru" },
            { "title": "Aland Islands", "value": "ax", "key": "ax" },
            { "title": "Faroe Islands", "value": "fo", "key": "fo" },
            { "title": "Malta", "value": "mt", "key": "mt" },
            { "title": "Moldova", "value": "md", "key": "md" },
            { "title": "Serbia", "value": "rs", "key": "rs" },
            { "title": "Ireland", "value": "ie", "key": "ie" },
            { "title": "Czech Republic", "value": "cz", "key": "cz" },
            { "title": "Montenegro", "value": "me", "key": "me" },
            { "title": "Bosnia And Herzegovina", "value": "ba", "key": "ba" },
            { "title": "France", "value": "fr", "key": "fr" },
            { "title": "Cyprus", "value": "cy", "key": "cy" },
            { "title": "Iceland", "value": "is", "key": "is" },
            { "title": "Estonia", "value": "ee", "key": "ee" },
            { "title": "Ukraine", "value": "ua", "key": "ua" },
            { "title": "Luxembourg", "value": "lu", "key": "lu" },
            { "title": "Slovenia", "value": "si", "key": "si" },
            { "title": "Isle of Man", "value": "im", "key": "im" },
            { "title": "Macedonia", "value": "mk", "key": "mk" },
            { "title": "Poland", "value": "pl", "key": "pl" },
            { "title": "Albania", "value": "al", "key": "al" },
            { "title": "Belarus", "value": "by", "key": "by" },
            { "title": "Andorra", "value": "ad", "key": "ad" },
            { "title": "Hungary", "value": "hu", "key": "hu" },
            { "title": "Bulgaria", "value": "bg", "key": "bg" },
            { "title": "Gibraltar", "value": "gi", "key": "gi" },
            { "title": "Turkey", "value": "tr", "key": "tr" },
            { "title": "Greenland", "value": "gl", "key": "gl" },
            { "title": "Lithuania", "value": "lt", "key": "lt" },
            { "title": "Slovak Republic", "value": "sk", "key": "sk" },
            { "title": "Romania", "value": "ro", "key": "ro" },
            { "title": "Liechtenstein", "value": "li", "key": "li" },
            { "title": "Latvia", "value": "lv", "key": "lv" },
            { "title": "Switzerland", "value": "ch", "key": "ch" },
            { "title": "Finland", "value": "fi", "key": "fi" },
            { "title": "Germany", "value": "de", "key": "de" },
            { "title": "Great Britain", "value": "gb", "key": "gb" },
            { "title": "Sweden", "value": "se", "key": "se" }
        ],
    },
    {
        title: "Africa",
        value: "4",
        key: "4",
        children: [
            { "title": "Algeria", "value": "dz", "key": "dz" },
            { "title": "Tunisia", "value": "tn", "key": "tn" },
            { "title": "South Africa", "value": "za", "key": "za" },
            { "title": "Morocco", "value": "ma", "key": "ma" },
            { "title": "Egypt", "value": "eg", "key": "eg" },
            { "title": "Kenya", "value": "ke", "key": "ke" }
        ],
    },
    {
        title: "Oceania",
        value: "5",
        key: "5",
        children: [
            { "title": "Australia", "value": "au", "key": "au" },
            { "title": "New Zealand", "value": "nz", "key": "nz" }
        ],
    },
];
