export const btnList = [
    { name: 'Generate' },
    { name: 'Reset' },
    { name: 'Copy' },
    { name: 'Shuffle' },
    { name: 'Download' },
    { name: 'Clear list' },
];

export const treeData = [
    {
        title: "Website",
        value: "1",
        key: "1",
        children: [
            { title: "Footsite/YeezySupply", value: "us" },
            { title: "Footlocker-CA", value: "ca" },
            { title: "Footlocker-EU", value: "de,gb,nl,fr" },
            { title: "Footlocker-AU", value: "au,nz" },
            { title: "Footlocker-SG", value: "sg,my,hk" }
        ],
    },
    {
        title: "Asia",
        value: "2",
        key: "2",
        children: [
            { title: "Thailand", value: "th" },
            { title: "China", value: "cn" },
            { title: "Indonesia", value: "id" },
            { title: "Taiwan", value: "tw" },
            { title: "Yemen", value: "ye" },
            { title: "Philippines", value: "ph" },
            { title: "India", value: "in" },
            { title: "Pakistan", value: "pk" },
            { title: "South Korea", value: "kr" },
            { title: "Japan", value: "jp" },
            { title: "Malaysia", value: "my", },
            { title: "Saudi Arabia", value: "sa" },
            { title: "Vietnam", value: "vn" },
            { title: "Hong Kong", value: "hk" },
            { title: "Syria", value: "sy" },
            { title: "Singapore", value: "sg" }
        ],
    },
    {
        title: "America",
        value: "3",
        key: "3",
        children: [
            { title: "Chile", value: "cl" },
            { title: "Uruguay", value: "uy" },
            { title: "Dominican Republic", value: "do" },
            { title: "Venezuela", value: "ve" },
            { title: "Brazil", value: "br" },
            { title: "Argentina", value: "ar" },
            { title: "United States", value: "us2" },
            { title: "Colombia", value: "co" },
            { title: "Canada", value: "ca" },
            { title: "Mexico", value: "mx" }
        ],
    },
    {
        title: "Europe",
        value: "4",
        key: "4",
        children: [
            { title: "Bailiwick of Jersey", value: "je" },
            { title: "Italy", value: "it" },
            { title: "Monaco", value: "mc" },
            { title: "Belgium", value: "be" },
            { title: "Spain", value: "es" },
            { title: "Austria", value: "at" },
            { title: "Croatia (Hrvatska)", value: "hr" },
            { title: "Denmark", value: "dk" },
            { title: "Greece", value: "gr" },
            { title: "Norway", value: "no" },
            { title: "Guernsey", value: "gg" },
            { title: "Netherlands", value: "nl" },
            { title: "San Marino", value: "sm" },
            { title: "Portugal", value: "pt" },
            { title: "Russia", value: "ru" },
            { title: "Aland Islands", value: "ax" },
            { title: "Faroe Islands", value: "fo" },
            { title: "Malta", value: "mt" },
            { title: "Moldova", value: "md" },
            { title: "Serbia", value: "rs" },
            { title: "Ireland", value: "ie" },
            { title: "Czech Republic", value: "cz" },
            { title: "Montenegro", value: "me" },
            { title: "Bosnia And Herzegovina", value: "ba" },
            { title: "France", value: "fr" },
            { title: "Cyprus", value: "cy" },
            { title: "Iceland", value: "is" },
            { title: "Estonia", value: "ee" },
            { title: "Ukraine", value: "ua" },
            { title: "Luxembourg", value: "lu" },
            { title: "Slovenia", value: "si" },
            { title: "Isle of Man", value: "im" },
            { title: "Macedonia", value: "mk" },
            { title: "Poland", value: "pl" },
            { title: "Albania", value: "al" },
            { title: "Belarus", value: "by" },
            { title: "Andorra", value: "ad" },
            { title: "Hungary", value: "hu" },
            { title: "Bulgaria", value: "bg" },
            { title: "Gibraltar", value: "gi" },
            { title: "Turkey", value: "tr" },
            { title: "Greenland", value: "gl" },
            { title: "Lithuania", value: "lt" },
            { title: "Slovak Republic", value: "sk" },
            { title: "Romania", value: "ro" },
            { title: "Liechtenstein", value: "li" },
            { title: "Latvia", value: "lv" },
            { title: "Switzerland", value: "ch" },
            { title: "Finland", value: "fi" },
            { title: "Germany", value: "de" },
            { title: "Great Britain", value: "gb" },
            { title: "Sweden", value: "se" }
        ],
    },
    {
        title: "Africa",
        value: "5",
        key: "5",
        children: [
            { title: "Algeria", value: "dz" },
            { title: "Tunisia", value: "tn" },
            { title: "South Africa", value: "za" },
            { title: "Morocco", value: "ma" },
            { title: "Egypt", value: "eg" },
            { title: "Kenya", value: "ke" }
        ],
    },
    {
        title: "Oceania",
        value: "6",
        key: "6",
        children: [
            { title: "Australia", value: "au" },
            { title: "New Zealand", value: "nz" }
        ],
    },
];
